### ISSUE TITLE
secret-path use

### ISSUE THREAD

**Issue by ismael-ull-db** [Infisical/secrets-action#4]
Can you explain a little better in the documentation about the "**secret-path**" input?
I understand that it refers to the folders that may exist within the inphysical project, correct? But how should it be used?
Suppose inside my project I have a folder called "**subfolder**" and I want to inject them. How should I configure it?

```
secret-path: subfolder
secret-path: /subfolder
secret-path: /subfolder/
```

Another option?

**Comment by comatory** [comment]
Yes the lack of documentation and examples is not good. I will give you an example that worked for me, my project in Infisical contains folder `CI` so I the way I call the action is this:

```yaml
- uses: Infisical/secrets-action@v1.0.7
  with:
    client-id: ${{ secrets.INFISICAL_MACHINE_IDENTITY_CLIENT_ID}}
    client-secret: ${{ secrets.INFISICAL_MACHINE_IDENTITY_CLIENT_SECRET }}
    env-slug: "<my-env-slug>"
    project-slug: "<my-project-slug>"
    recursive: true
    secret-path: "/CI"
```

So I start at the root with `/` and add the folder. It seems to work. When your workflow fails, check "Enable debug logging" and the action should log out what secret IDs it obtained in an array.
