### ISSUE TITLE
Cannot read properties of undefined (reading 'length') - when include-imports: false [BUG]

### ISSUE THREAD

**Issue by mtracz** [Infisical/secrets-action#7]
Hi, we encountered some issue with `include-imports` param.

We have project with secrets in dir `/deployment`.
In this project there are any imported secrets.
ACL config in Infisical is correct.

When we set `include-imports: false` we got error in Github Actions log:
```
Error: Error:
Error: Cannot read properties of undefined (reading 'length')
```
If `include-imports: true` it's working fine.

Action config:
```
- name: fetch project deployment secrets
        uses: Infisical/secrets-action@v1.0.7
        with:
          domain: https://self-hosted.example.com
          client-id: <secret>
          client-secret: <secret>
          project-slug: example
          env-slug: staging
          secret-path: /deployment
          export-type: env
          recursive: false
          include-imports: false
```

I think the issue might be here, because maybe there is no `imports` in the response when `include_imports` param is set to false.:

- https://github.com/Infisical/secrets-action/blob/a861a80390155803e14720b6886100b8d45fca1f/infisical.js#L85-L87

Based on API reference: https://infisical.com/docs/api-reference/endpoints/secrets/list
`imports` are set as not required in the response.

Action version: v1.0.7
Infisical self-hosted version: v0.104.4-postgres
